import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8f9ff",
        "on-background": "#171c24",
        surface: "#f8f9ff",
        "surface-dim": "#d5dae5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff3ff",
        "surface-container": "#e9eef9",
        "surface-container-high": "#e4e8f4",
        "surface-container-highest": "#dee2ee",
        "surface-variant": "#dee2ee",
        "on-surface": "#171c24",
        "on-surface-variant": "#3f4942",
        "inverse-surface": "#2b3139",
        "inverse-on-surface": "#ecf1fc",
        outline: "#6f7a72",
        "outline-variant": "#bfc9c0",
        "surface-tint": "#1d6b48",
        primary: "#196946",
        "on-primary": "#ffffff",
        "primary-container": "#37825d",
        "on-primary-container": "#f6fff6",
        "inverse-primary": "#8bd6ab",
        "primary-fixed": "#a6f3c6",
        "primary-fixed-dim": "#8bd6ab",
        "on-primary-fixed": "#002112",
        "on-primary-fixed-variant": "#005233",
        secondary: "#5b5e66",
        "on-secondary": "#ffffff",
        "secondary-container": "#dddfe9",
        "on-secondary-container": "#5f636a",
        "secondary-fixed": "#dfe2eb",
        "secondary-fixed-dim": "#c3c6cf",
        "on-secondary-fixed": "#181c22",
        "on-secondary-fixed-variant": "#43474e",
        tertiary: "#8f454c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ad5d63",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdadb",
        "tertiary-fixed-dim": "#ffb2b6",
        "on-tertiary-fixed": "#3d050f",
        "on-tertiary-fixed-variant": "#753137",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "tap-target": "44px",
      },
      fontFamily: {
        sans: ["Inter", "Arial", "sans-serif"],
      },
      fontSize: {
        "major-title": ["32px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "600" }],
        "screen-title": ["24px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "600" }],
        "section-title": ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        body: ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        secondary: ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        metadata: ["12px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
      },
      boxShadow: {
        none: "none",
      },
    },
  },
  plugins: [],
};

export default config;
